stages: [verify, build]

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"

verify_runner:
  stage: verify
  tags: [docker, local]
  script:
    - docker version
    - echo "✅ Runner can talk to the host Docker engine"

build_hello_image:
  stage: build
  tags: [docker, local]
  script:
    - echo 'FROM alpine:3.20' > Dockerfile
    - echo 'CMD ["sh","-lc","echo Hello from GitLab CI!"]' >> Dockerfile
    - docker build -t hello-gitlab-ci:local .
    - docker run --rm hello-gitlab-ci:local
